
###
POST https://localhost:3000/api/posts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNUMTAwOTExMTQiLCJ1c2VyaWQiOiI2NTI1ZjE3ZjEwNmViYmNlOTQ0ZGE3ZmMiLCJpYXQiOjE2OTY5ODU1MDMsImV4cCI6MTY5Njk5MjcwM30.DPQE33lONgQw1Deg2rcOn0aK6DHKLDU2jJL_tQwVc2I

{
    "postName": "Homework",
    "postDescription": "APDS is great but JS isnt"
}

###
GET https://localhost:3000/api/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyNCIsInVzZXJpZCI6IjY1MTg3NDZjNGM3M2UwMjE1MDFhOTBkMCIsImlhdCI6MTY5NjE1MDY4NSwiZXhwIjoxNjk2MTU3ODg1fQ.YuyGnFXkrVOMuk1UME9u_6mn9fZ9kpqUXtgSkP_lejc

###
DELETE https://localhost:3000/api/posts/Homework HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNUMTAwOTExMTQiLCJ1c2VyaWQiOiI2NTI1ZjE3ZjEwNmViYmNlOTQ0ZGE3ZmMiLCJpYXQiOjE2OTY5ODU1MDMsImV4cCI6MTY5Njk5MjcwM30.DPQE33lONgQw1Deg2rcOn0aK6DHKLDU2jJL_tQwVc2I

###
GET https://localhost:3000/api/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNUMTAwOTExMTQiLCJ1c2VyaWQiOiI2NTI1ZjE3ZjEwNmViYmNlOTQ0ZGE3ZmMiLCJpYXQiOjE2OTY5OTQ3NjcsImV4cCI6MTY5NzAwMTk2N30.bpSQzBYkvCI5StGr1xX9BNuoweSyTeURY_QSZqy90-A
###
POST https://localhost:3000/api/users/signup HTTP/1.1
content-type: application/json


{
    "username": "ST10091114",
    "password": "RandomPassword"
}

###
POST  https://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "ST10091114",
    "password": "RandomPassword"
}